version: "3.8"

services:
  product:
    image: restore/product:latest
    deploy:
      replicas: 1
    volumes:
      - "./uploads:/go/src/uploads"
    networks:
      main:
        aliases:
          - product
networks:
  main:
    external: true